### ISSUE TITLE
The subicons are not displayed on the card_room card

### ISSUE THREAD

**Issue by perezrojose** [UI-Lovelace-Minimalist/UI#1457] opened 2024-02-11 23:25 UTC
**Describe the bug**
The subicons are not displayed on the card_room card. This error appeared after updating to version 2024.2.1 from version 2024.1.6. I tried reloading the page and it didn't work. Reverting to version 2024.1.6 everything works correctly again.

**To Reproduce**

1. Upgrade to 2024.2.1
2. See error

**Screenshots**
![pantalla - copia (Small)](https://github.com/UI-Lovelace-Minimalist/UI/assets/84590437/849efcad-95cc-4019-84a9-b154ecaf0279)

**Comment by Luke15153** [comment] 2024-02-12 08:28
duplicate of https://github.com/UI-Lovelace-Minimalist/UI/issues/1454

**Closed** 2024-02-13 04:15 UTC
Labels: :bug: bug

**Comment by perezrojose** [comment] 2024-02-13 04:26
I was reviewing all the comments of the previous case #1454 , I updated the button-card file to the newest version and the problem was solved.

I appreciate all your help
