### ISSUE TITLE
Tabbar navigation

### ISSUE THREAD

**Issue by thomasfals** [UI-Lovelace-Minimalist/UI#346] opened 2022-01-28 07:38 UTC
**Is your feature request related to a problem? Please describe.**
Navigating between views is not optimal on mobile devices. 

**Describe the solution you'd like**
I suggest a tabbar to be placed along the bottom of the viewport with icons from the view. Much like navigation known from native IOS and Android apps. In some situations the width of the tabbar will not be able to accommodate all icons. In such cases the a transparency gradient can be placed over the last icon in the tabbar to illustrate additional content. The user would swipe to reveal more icons.  

**Describe alternatives you've considered**
Either you have to use desktop theme to have the top navigation visible. This requires a lot of stretching on larger devices.  Alternatively you have to use Swipe but that is not ideal either as you have to be carefull where you place the finger when doing swipe.  

**Additional context**
I have attached a mockup of how the tabbar could be presented. 

![tabbar](https://user-images.githubusercontent.com/506474/151506221-193f7f9f-a01a-4c09-a94d-36adba5e52a5.png)

**Comment by stokkie90** [comment] 2022-01-28 09:52
We need some java-script that will edit the `app-header` And add the following ccs-style: `top: auto; bottom: 0px;` in the integration i can then load that javascript file. 

![Screenshot from 2022-01-28 10-51-31](https://user-images.githubusercontent.com/10831825/151525494-2d344ae0-06f9-4e24-917d-53847946c005.png)

**Comment by r0binj** [comment] 2022-01-28 17:55
I would love to have the bar at the bottom with a tablet too 🙂

**Comment by httpedo13** [comment] 2022-01-28 22:53
![Schermata 2022-01-28 alle 23 52 19](https://user-images.githubusercontent.com/40502451/151632577-2718ba50-9ca3-4a32-9bda-2a6359a82adb.png)

in my opinion this is the best solution, but it requires a custom view to place the card in the footer.

**Comment by thomasfals** [comment] 2022-01-29 07:18
> ![Schermata 2022-01-28 alle 23 52 19](https://user-images.githubusercontent.com/40502451/151632577-2718ba50-9ca3-4a32-9bda-2a6359a82adb.png)
> 
> in my opinion this is the best solution, but it requires a custom view to place the card in the footer.

I agree that it looks great but it will require the user to do an additional press when changing view. This is why you never see such a solution for tabbar navigation in native apps. 

Looks great but bad UX.

**Comment by Ned-Tom** [comment] 2022-02-03 17:46
@dmatik made a theme that could move his tab bar, here is his repository : https://github.com/dmatik/homeassistant-config.
So i did some tweaking my self and made something similar what @thomasfals  made, here is my theme file : [Ned-Tom](https://gist.github.com/Ned-Tom)/[minimalist-navbar.yaml](https://gist.github.com/Ned-Tom/b531422d68af4e810e2e7eb7fb21fb4e), Hope this helps 👍🏻

**Comment by dmatik** [comment] 2022-02-03 19:45
> @dmatik made a theme that could move his tab bar, here is his repository : https://github.com/dmatik/homeassistant-config.
> 
> So i did some tweaking my self and made something similar what @thomasfals  made, here is my theme file : [Ned-Tom](https://gist.github.com/Ned-Tom)/[minimalist-navbar.yaml](https://gist.github.com/Ned-Tom/b531422d68af4e810e2e7eb7fb21fb4e), Hope this helps 👍🏻 

Hey,
Any chance you can figure out how to make the whole header height as 80px without breaking the UI when scrolling up and down? You see on iPhone the original header when you put it down it is very hard to use. Have to make it wider.

**Comment by Ned-Tom** [comment] 2022-02-03 21:27
> > @dmatik made a theme that could move his tab bar, here is his repository : https://github.com/dmatik/homeassistant-config.
> > So i did some tweaking my self and made something similar what @thomasfals  made, here is my theme file : [Ned-Tom](https://gist.github.com/Ned-Tom)/[minimalist-navbar.yaml](https://gist.github.com/Ned-Tom/b531422d68af4e810e2e7eb7fb21fb4e), Hope this helps 👍🏻
> 
> Hey, Any chance you can figure out how to make the whole header height as 80px without breaking the UI when scrolling up and down? You see on iPhone the original header when you put it down it is very hard to use. Have to make it wider.

I don't exactly understand what the problem is, but i did test the theme on my ipad and found multiple issues whit the theme.
so i did some fixing on my own version that is very comparable to your original version.
You can find it here : [minimalist-navbar-alt.yaml](https://gist.github.com/Ned-Tom/6229d80c9f8b8f5450a44c4dca18f775)
![mobile](https://user-images.githubusercontent.com/3158863/152430413-a5835756-39db-4a15-a66f-2b90ef9cc2ad.png)
![tablet](https://user-images.githubusercontent.com/3158863/152430426-26ef9b2a-6d37-4a64-881e-bff6cdc49970.png)

This version should also be compatible whit IOS Android and Desktop.
I didn't test whit iPhone or android whit an notch because i don't have such devices. 

Also i don't' know if this is the best place to discus this issue because it goes off topic therefore i don't' know a better place yet

I hope that i can help and would love to hear what you think.

**Comment by sorted01** [comment] 2022-02-03 21:31
Wow, that looks promissing :) Thank you for your work!
 Stupid question :/ how to implement it?

**Comment by Ned-Tom** [comment] 2022-02-03 21:42
@sorted01 Thanks.
The YAML file posted above is a theme file so when you download this file and place it in your theme folder it should work.
The tabs are the views inside your ui-lovelace.yaml, should work whit text and or icons like shown above.

**Comment by stokkie90** [comment] 2022-02-03 21:44
How will it behave if you have more views on mobile. Will it give you a slider or?

**Comment by Ned-Tom** [comment] 2022-02-03 21:50
> How will it behave if you have more views on mobile. Will it give you a slider or?

It's limited to 4 at the moment , 
but when you have more than 4 views you can swipe on a touch screen to view the other, does not work on desktop / no fix for yet.
you can change the amount visible inside the theme file.

**Comment by dmatik** [comment] 2022-02-04 00:14
@Ned-Tom 
Thanks man!
My problem was not with iOS itself, but specifically with iPhone, where we have always a line in the bottom of the screen. This is how iPhone UI designed. So all buttons of the footer bar in all the applications must be above it. I used to made the footer 80px before when was using it. Now I tried and it is not working properly anymore, something changed in recent HA update.

**Comment by sorted01** [comment] 2022-02-04 06:59
@Ned-Tom  thank you! It's working :)

**Comment by Ned-Tom** [comment] 2022-02-04 08:23
> @Ned-Tom Thanks man! My problem was not with iOS itself, but specifically with iPhone, where we have always a line in the bottom of the screen. This is how iPhone UI designed. So all buttons of the footer bar in all the applications must be above it. I used to made the footer 80px before when was using it. Now I tried and it is not working properly anymore, something changed in recent HA update.

Did i fix your issue whit this theme?
Because i fount that on Ipad i needed more white space behind the home button, a assume this was your issue also?

**Comment by dmatik** [comment] 2022-02-04 08:28
@Ned-Tom 
Well. I could figure out the space issue. No problem. 
But once I am increasing the header height to 80px, for sone reason every time I reload the page the top part of the whole page is got cut. I am switching to other view, going back, and it stop being cut. Until next time I totally refresh the page. 
Like some styles are not consistent. Very strange. 😀

**Comment by peetereczek** [comment] 2022-02-04 09:57
I'm testing on Android and there are some minor issues as well, can be corrected easily

What I changed for now is top spacing from system top bar. Added 'margin-top: 5px;' to ha-app-layout property. Results below:

![Screenshot_20220204-105347_Home Assistant.png](https://user-images.githubusercontent.com/42431204/152509028-594140d9-d4c8-4a8e-8da6-4f47718b7f46.png)

**Comment by stokkie90** [comment] 2022-02-04 11:49
Pretty basic

```yaml
  # Move navbar
  card-mod-root-yaml: |
    .: |
      @media (orientation: portrait) {
        a.menu-link[target="_blank"], ha-button-menu, ha-menu-button, [main-title] {
              display: none !important;
        }
        app-toolbar {
              padding-right: 0px;
              padding-left: 0px;
        }
      }
      app-header {
        top: auto;
        bottom: 0px;
      }
      #view {
        margin-top: -60px;
      }
```


![Screenshot_20220204-123750](https://user-images.githubusercontent.com/10831825/152523146-1ef7b6fb-5cd1-40a4-af57-78e7de957c98.jpg)

**Comment by Ned-Tom** [comment] 2022-02-04 12:01
I move my version of the theme to his own repository, because its unofficial and i can't give support trough this Issue.
You can find it here : https://github.com/Ned-Tom/Lovelace-Minimalist-Tapbar-Theme
Maybe in the future it can become an official theme but its still in consideration so for the time being this gone be it.
Feel free to open an new issue and help improve the theme from there 👍🏻

**Comment by stokkie90** [comment] 2022-02-04 12:09
You are free to make a PR. Shouldn't be hard to include it. I can help you with the python changes needed.

**Comment by Ned-Tom** [comment] 2022-02-04 12:13
> You are free to make a PR. Shouldn't be hard to include it. I can help you with the python changes needed.

Would be awesome, but never don it before.
what do you suggest, add my theme as is to dev branch of the repository ?

**Comment by stokkie90** [comment] 2022-02-04 12:19
Are you by any chance on our discord server? You can reach out to me there. I could help you along. 

But to do it. Fork the repo. Make your change and create a PR to the dev branch.

**Comment by sorted01** [comment] 2022-02-13 15:13
Hi @Ned-Tom
At the beginning it worked fine. Now all of a sudden (maybe because of an update, I don't know...) it looks like that. Can you support me? Would be cool :) thank you!
![Screenshot_20220213-161312_Home Assistant](https://user-images.githubusercontent.com/83211473/153759754-22bb1149-0ea3-407a-a48d-ccee9e1ae71e.jpg)

**Comment by Ned-Tom** [comment] 2022-02-15 08:51
Hello @sorted01 ,

I have seen this issue before but still not really understand way it happens.
The "PR" is already merged whit the Development version of Ui-Minilmalist and i did add a static height to the tapbar.

Can you check if you got the same issue when adding the Dev version of Ui-Minilmalist to you configuration?

**Comment by danieldevos90** [comment] 2022-02-16 19:13
Hey @Ned-Tom I use the HA app on iOS and got also the issue that the menu is not showing.
![IMG_E684F30CFE88-1](https://user-images.githubusercontent.com/86712582/154338664-848200a3-6b3a-47cd-8033-4a5418ecdad3.jpeg)

Can you help?

**Comment by danieldevos90** [comment] 2022-02-18 15:12
Hello @Ned-Tom, 

I changed it in minimalist-mobile-tapbar.yaml. In your own template it was already set.
After I changed it is still occuring unfortunately.

I use an Iphone 13 but I'm unable to debug it...

Greets,

Daniel

**Comment by danieldevos90** [comment] 2022-02-18 15:42
Okay, I got the fix for my iphone:

`@media (orientation: portrait) {
        a.menu-link[target="_blank"], ha-button-menu, ha-menu-button, [main-title] {
          display: none !important;
        }
        app-toolbar {
          height: 100px !important;
          padding-right: 0px;
          padding-left: 10px;
        }
      }`

Not the most ideal one but it works

**Comment by Ned-Tom** [comment] 2022-02-18 18:04
> Also popping in to say I'm getting the weird squished bar on my iPhone 12 in the HomeAssistant app only. If i load HomeAssistant via Safari/web browser, it loads a-ok.

is it possible to send an screenshot ?
i'm currently trying to improve this theme.

**Comment by miniminne** [comment] 2022-02-18 18:09
> > Also popping in to say I'm getting the weird squished bar on my iPhone 12 in the HomeAssistant app only. If i load HomeAssistant via Safari/web browser, it loads a-ok.
> 
> is it possible to send an screenshot ? i'm currently trying to improve this theme.

Of course! Sorry I forgot those. 

Safari on iOS: 
![IMG_1556](https://user-images.githubusercontent.com/8529568/154738430-3088d356-f6cb-4995-bef4-202cc534e947.jpeg)

HomeAssistant App (and PWA(?) view when adding to the iPhone homescreen):
![IMG_1555](https://user-images.githubusercontent.com/8529568/154738519-32db85ce-85a6-4611-bdac-52dc2d3b7fb6.PNG)

**Comment by Ned-Tom** [comment] 2022-02-18 18:22
I did changes some things in the theme file, i hope to resolve some issues whit this theme.
Can you test this for me @miniminne @danieldevos90 @sorted01 .

You find my current dev theme here : https://gist.github.com/Ned-Tom/666bd5be5cbd6ac355e82a0f08e85acf

Hope this helps and if there more issues on this theme you can comment them thee also.
when that dev theme is ok i wil create a PR to make it final.

Also @stokkie90 @thomasfals i think that this feature request ma be closed

Greetings Tom.

**Comment by Ned-Tom** [comment] 2022-02-18 19:40
weird, 
I did test it on my android phone (Samsung A8 2018) and Ipad (Ipad air 4) and there it forks fine.
It looks like an scaling issue

did you clear the cashes on your devices because it seems that the HA App keeps caching the theme ?

**Comment by miniminne** [comment] 2022-02-18 19:52
Yup! Its just weird to me that Safari on iOS displays it properly but the HA app/PWA fails to render it properly. 

I played around with the padding and various sizes, but to no avail. 

I don't know if the other folks seem to still be having the issue, I am running HAOS 2022.2.8 & the app is iOS 2022.2 if that helps any.

iOS App after adding the updated code/overwriting the current theme file: 
![IMG_D958349326F8-1](https://user-images.githubusercontent.com/8529568/154752130-525cc303-09f6-4d12-8136-3857bc82b181.jpeg)

**Comment by Ned-Tom** [comment] 2022-02-18 20:01
The problem i came across in IOS (IpadOS) and Android when using the official HA app that sometimes you need to completely clear the app before the theme will apply correctly.
when i try this on the desktop i have this issue sometimes, so i had to disable caching in my browser to properly view if it does update. this does apply also on the mobile browser but didn't test that.

**Comment by miniminne** [comment] 2022-02-18 20:15
> The problem i came across in IOS (IpadOS) and Android when using the official HA app that sometimes you need to completely clear the app before the theme will apply correctly. when i try this on the desktop i have this issue sometimes, so i had to disable caching in my browser to properly view if it does update. this does apply also on the mobile browser but didn't test that.

Unfortunately I did reset the app/reset the cache in the app a few times to no success. I'm starting to wonder if its a bug/change in iOS's webviews or the app itself for iOS.

**Closed** 2022-04-04 06:53 UTC
Labels: :bulb: feature
