### ISSUE TITLE
ui_lovelace_minmalist custom element doesn't exist: 

### ISSUE THREAD

**Issue by smartypantsuk** [UI-Lovelace-Minimalist/UI#1269] opened 2023-04-10 10:17 UTC
I have tried installing UI-Lovelace-minimalist multiple times on fresh HA OS install only for the same error to occur consistently every time. The initial install via HACS works fine, no errors.  Upon viewing the default Lovelace dashboard, all the errors display as in the screenshot below. 
![lovelace-dashboard](https://user-images.githubusercontent.com/58052383/230881672-c5b6ae86-4a73-438b-8bb5-73db502a18c4.jpg)

I have verified installation steps. I have reloaded ui_lovelace_minimalist from the developer tools sections multiple times. I have refreshed browser cache multiple times. I have even installed a different browser to try a fresh, still the same. I have restarted HA multiple times.

I have tried adding the urls in the UI Resource section:

- /hacsfiles/button-card/button-card.js
- /hacsfiles/button-card/layout-card.js
- /hacsfiles/button-card/simple-weather-card.js
- /hacsfiles/button-card/state-switch.js
- /hacsfiles/l/mini-graph-card-bundle.js
- /hacsfiles/light-entity-card/light-entity-card.js
- /hacsfiles/lovelace-auto-entities/auto-entities.js
- /hacsfiles/lovelace-card-mod/card-mod.js
- /hacsfiles/lovelace-layout-card/layout-card.js
- /hacsfiles/lovelace-state-switch/state-switch.js
- /hacsfiles/mini-media-player/mini-media-player-bundle.js
- /hacsfiles/my-cards/my-cards.js
- /hacsfiles/simple-weather-card/simple-weather-card-bundle.js

Nothing seems to work as it should. So I looked for the correct files in the config folders and they are present.
However, something I have noticed is that there are no files in config/www/community folder!
My understanding was that hacfiles directory is a type of symlink to community folder, so the files should exist in there should they not? I have used HACS for a few weeks with no problems. I have around 6 integrations installed via HACS and working fine.

I have tried installing the cards manually into community folder, this doesn't fix anything either so I've now removed them.
There are no errors in the system logs.

I am not sure what to try next, except this happens each time I run a clean install of HA OS or refresh from a working snapshot.

Thanks

**Comment by sauliusesu** [comment] 2023-04-11 09:17
Same is happening for me. Minimalist stopped working for me after Home Assistant Core update. I restored HAC to version 2023.3.6 and everything is working again.

**Comment by smartypantsuk** [comment] 2023-04-11 09:18
> Same is happening for me. Minimalist stopped working for me after Home Assistant Core update. I restored HAC to version 2023.3.6 and everything is working again.

I think it told me to update before I could install one of the required items,  though I fail to remember which.

**Comment by droserHA** [comment] 2023-04-13 15:32
the same! does not work.

**Comment by sauliusesu** [comment] 2023-04-20 18:39
The latest minimalist hotfix has been installed along with all the other HA updates. Still unusable, same errors as in original post. Uninstalling..

**Comment by ChrisK91** [comment] 2023-05-07 13:17
Have you run frontend.reload_themes as stated on the release page?

**Comment by droserHA** [comment] 2023-05-07 16:10
The author does not deal with problems, as I understand it. It's a pity!

**Comment by ChrisK91** [comment] 2023-05-07 16:51
Are you using the "Include Custom Cards"  option or have you installed the required third party cards manually. I've also found that the custom cards now require to be individually selected in the integration options. I think the documentation is a bit outdated in that regard.

**Comment by basbruss** [comment] 2023-05-07 16:59
@droserHA What do you mean by the author does not deal with problems. Every bug caused by the latest HA release are fixed within days or even in hours...

The type of error mentioned above is one caused by some wrong config/misunderstanding on how to use custom frontend components with HACS.

Really nothing to do with this project, only that it uses some of the components.

There are plenty guides for HACS and closed issues with similar errors.

**Comment by droserHA** [comment] 2023-05-07 17:18
@basbruss I didn't mean to offend anyone. After updating HA to 2023.4+ cards stopped working. People have similar problems and tickets are not closed. I like it very much. A lot of work has been done, but now it does not work and I do not know the reason.

**Comment by purevet** [comment] 2023-06-08 18:21
I was having these same issues, along with other ones including being unable to update HASSOS at all. So after a full wipe and reinstall i was still confronted by not being able to use ANY of the HACs lovelace cards.
However i have found a solution that works in my case.

Download/install Card ect via hacs
Note install directory. Usually something to the affect of :
/local/community/xx/xx.js
Where local is your “local config directory” and xx is the name of your particular card
Then in the standard Sidebar UI go to
Settings > Dashboards
Click the 3 dots in the top Right
Click Resources
Click “+ Add Resource”
in the URL section paste the location you noted earlier
Capture34

As an example ill use the Surveillance-card
/local/community/surveillance-card/surveillance-card.js
Ensure that “Resource type” - JavaScript Module - was Auto selected (if not select it)
Then click create.
Your card should be usable at that point.
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/40616921/c2b0f39a-93c9-4a4f-9e25-5e1c6c538de1)

This is a silly thing to do for something that should be automatically picked up and detected and has been in the past. Not sure what broke in OS version 10.2, but having to manually enter these is annoying.

**Comment by TMRE** [comment] 2023-09-25 21:02
I am having the same issue after a new install. Any solutions?

**Comment by shodushi** [comment] 2023-11-13 18:34
I fixed mine with:
https://github.com/UI-Lovelace-Minimalist/UI/issues/1302#issuecomment-1808771294

**Comment by wilbiev** [comment] 2024-12-30 15:16
Merging this issue with #1302

**Closed by wilbiev** 2024-12-30 15:16 UTC
Labels: :bug: bug
