### ISSUE TITLE
Light slider bar has no color

### ISSUE THREAD

**Issue by rick2909** [UI-Lovelace-Minimalist/UI#275] opened 2022-01-19 23:18 UTC
**Describe the bug**
When the new light card is used with the slider enabled, the slider bar has no color of how full it is.

It works when the option `ulm_card_light_enable_color` is set to `true`.

this is in the current dev version

**To Reproduce**

1. create a `card_light`
2. add as variable `ulm_card_light_enable_slider: true`

**Expected behavior**
that the bar still shows with the current color of the light

**Screenshots**
![image](https://user-images.githubusercontent.com/28780475/150233376-b01cd4f7-255f-4920-bc32-cca35bc9d5a1.png)

**Comment by basbruss** [comment] 2022-01-20 06:35
I can't reproduce the bug with the YAML code from the HACS version.
Your icon should also have a yellow color if the card is working correctly.
```
- type: 'custom:button-card'
   template: card_light
   entity: light.hue_go
   variables:
     ulm_card_light_enable_slider: true
```
Leads to in my system 
<img width="497" alt="Screen Shot 2022-01-20 at 07 28 28" src="https://user-images.githubusercontent.com/68892092/150285402-3329370a-2ea6-4eca-998b-6fc2e779201b.png">
<img width="401" alt="Screen Shot 2022-01-20 at 07 29 43" src="https://user-images.githubusercontent.com/68892092/150285537-5fa382aa-fd43-4df5-85cd-5c64e9612e69.png">

But I did notice when the dark mode is applied the text stays yellowish if the light is turned off.
I will test this card more today with the recommend way of installing the HACS version instead of copying the code for the card to fix some bugs.

**Comment by basbruss** [comment] 2022-01-20 10:08
With the HACS installation I am also not able to reproduce the problem with the slider.
On mine systems it works as intended

**Comment by CM000n** [comment] 2022-01-21 09:53
Should be resolved with https://github.com/UI-Lovelace-Minimalist/UI/pull/277 in next release

**Closed by CM000n** 2022-01-21 09:53 UTC
Labels: :bug: bug
