### ISSUE TITLE
Floating button with list of areas

### ISSUE THREAD

**Issue by irmajavi** [UI-Lovelace-Minimalist/UI#347] opened 2022-01-28 13:06 UTC
**Is your feature request related to a problem? Please describe.**
I want to use the mobile theme but there is no easy clean way to access the other pages unless you add a lot of buttons to the first page to navigate to other pages.

**Describe the solution you'd like**
A think something like this floating button, like the one that appears at the button of the dashboard to add cards
![Screenshot_20220128-085325_Home Assistant](https://user-images.githubusercontent.com/61939978/151551249-53f20cca-f78a-41d1-ab57-db4e043da083.jpg)

**Describe alternatives you've considered**
When you click the floating button a menu appears with all your areas
![Screenshot_20220128-084737_Chrome](https://user-images.githubusercontent.com/61939978/151551603-f24e518d-c5d2-4f3f-97d8-3fea31827f55.jpg)

**Additional context**
The original design has this feature but in a footer bar
![Screenshot_20220128-084816_Chrome](https://user-images.githubusercontent.com/61939978/151551741-53663cd4-d331-4e61-95f6-3951e9ca3abc.jpg)

**Comment by httpedo13** [comment] 2022-01-28 23:01
@irmajavi yes, it would be great, but it requires a custom view to place the card in the footer.
https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-view

**Comment by CM000n** [comment] 2022-01-29 08:43
I will close this, because it is somehow a duplicate of https://github.com/UI-Lovelace-Minimalist/UI/issues/346
But thank you for your feedback

**Closed by CM000n** 2022-01-29 08:43 UTC
Labels: :bulb: feature
