### ISSUE TITLE
Grey border on grids

### ISSUE THREAD

**Issue by esesen1** [UI-Lovelace-Minimalist/UI#1088] opened 2022-11-10 14:06 UTC
**Describe the bug**
For a few days, the interface has been modified and, now, all those cards that use grids appear with all their elements with a gray border.

**To Reproduce**
Simply charging the interface.

**Expected behavior**
No border on grid elements.

**Screenshots**

![image](https://user-images.githubusercontent.com/76493763/201112687-bf5018e2-4a7d-4598-85fd-68795032d696.png)

**Comment by basbruss** [comment] 2022-11-10 14:12
Duplicate of #1082 and #1074

**Closed by basbruss** 2022-11-10 14:12 UTC
Labels: :bug: bug
